name: Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Setup git user
        run: |
          git config --global user.name "maciek-bot"
          git config --global user.email "maciek.gh.bot@gmail.com"

      - name: Set new version
        id: set_version
        # Currently, there is no way to customize PR title and commit message in the action. As a workaround,
        # we can use `changeset status` command to get the new version and then use it in the next steps.
        # 🔗 See: https://github.com/changesets/action/issues/303#issuecomment-1888167265
        run: |
          echo "NEW_VERSION=$(bun changeset status --output=release.json && jq -r '.releases[0].newVersion' release.json && rm release.json)" >> $GITHUB_OUTPUT

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          title: 'release v${{ steps.set_version.outputs.NEW_VERSION }}'
          commit: 'release v${{ steps.set_version.outputs.NEW_VERSION }}'
          setupGitUser: false
          publish: bun run publish
          version: bun run version
        env:
          GITHUB_TOKEN: ${{ secrets.GH_BOT_PAT }}
